u_l = min(sqrt(sum(op_u.^2,2)));
%ff = sqrt(sum(op_u.^2,2))>(u_l*1.2)*0;
if Dim==2
    p = scatter(op_pos(:,1),op_pos(:,2),...
        ones(size(op_t_id))*10,sqrt(sum(op_u.^2,2)),...
        'filled');
else
    p = scatter3(op_pos(:,1),op_pos(:,2),op_pos(:,3),...
        ones(size(op_t_id(:)))*10,sqrt(sum(op_u.^2,2)),...
        'filled');
end
pause(0.025)