if Dim==2
    p = scatter(op_pos(:,1),op_pos(:,2),...
        ones(size(op_t_id))*10,sqrt(sum((op_U.*op_r(:,1)).^2,2))+op_U(:,2)*0.5,...
        'filled');
else
    p = scatter3(op_pos(:,1),op_pos(:,2),op_pos(:,3),...
        ones(size(op_t_id))*10,sqrt(sum((op_U.*op_r(:,1)).^2,2)),...
        'filled');
end
pause(0.025)