% Plot OPs

f = figure();
hold on
ind_new = chain.List(:,1)+chain.List(:,2);
ind_old = chain.List(:,1)+chain.List(:,2)-1;
scatter3(...
    OPtmp_pos(ind_old-1,1),...
    OPtmp_pos(ind_old-1,2),...
    OPtmp_pos(ind_old-1,3),...
    'filled');

scatter3(...
    OPtmp_pos(ind_old-2,1),...
    OPtmp_pos(ind_old-2,2),...
    OPtmp_pos(ind_old-2,3),...
    'filled');

quiver3(...
    OPtmp_pos(ind_old-1,1),...
    OPtmp_pos(ind_old-1,2),...
    OPtmp_pos(ind_old-1,3),...
    OPtmp_pos(ind_old-2,1) - OPtmp_pos(ind_old-1,1),...
    OPtmp_pos(ind_old-2,2) - OPtmp_pos(ind_old-1,2),...
    OPtmp_pos(ind_old-2,3) - OPtmp_pos(ind_old-1,3))

for i_T = 1:length(T.D)
    %Plot circular Rotor
    phi = linspace(0,2*pi);
    r = T.D(i_T)/2;
    yR = r*cos(phi);
    zR = r*sin(phi);
    
    cR = [...
        -sin(T.yaw(i_T)),0;...
        cos(T.yaw(i_T)),0;
        0,1]*[yR;zR];
    
    cR = cR'+T.pos(i_T,:);
    plot3(cR(:,1),cR(:,2),cR(:,3),'k','LineWidth',2);
    plot3(...
        [T.pos(i_T,1),T.pos(i_T,1)],...
        [T.pos(i_T,2),T.pos(i_T,2)],...
        [0,T.pos(i_T,3)],...
        'k','LineWidth',1.5);
end
hold off

f.Units               = 'centimeters';
f.Position(3)         = 16.1; % line width
%f.Position(3)         = 8;

% Set font & size
set(f.Children, ...
    'FontName',     'Frontpage', ...
    'FontSize',     10);

set(gca,'LooseInset', max(get(gca,'TightInset'), 0.04))

% Export
f.PaperPositionMode   = 'auto';