function CpCtCq = import10MwCpCtCqfile()
%IMPORTFILE Import data from a text file
%  CPCTCQ = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as a table.
%
%  CPCTCQ = IMPORTFILE(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  CpCtCq = importfile("D:\bmdoekemeijer\My Documents\SurfDrive\MATLAB\APC_work\Cp_Ct_Cq.DTU10MW.txt", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 20-Jul-2020 12:37:30

%% Input handling

% If dataLines is not specified, define defaults
dataLines = [1, Inf];

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 1);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = "RotorperformancetablesfortheDTU_10MW_RWTwindturbine";
opts.VariableTypes = "string";

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "RotorperformancetablesfortheDTU_10MW_RWTwindturbine", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "RotorperformancetablesfortheDTU_10MW_RWTwindturbine", "EmptyFieldRule", "auto");

% Import the data
CpCtCq = readtable('Cp_Ct_Cq.DTU10MW.txt', opts);

end